version: '3.4'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: seat
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql
  seatservice:
    image: seatservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://root:password@host.docker.internal:3307/seat
      USER_SERVICE_ENDPOINT: http://localhost:8080
    ports:
      - 3001:3001
    depends_on:
      - mysql
volumes:
  my-db: